### PR TITLE
Add new fields from metadata 2.1

### PR DESCRIPTION
**Pull request by kosmos342**
closes https://github.com/yola/yolapi/issues/52

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by jamesodo** [comment]
I think the 2 new fields need to be added to [`display_sort`](https://github.com/yola/yolapi/blob/6930ca2e681f5f778be2f4063d47e2b4eeb3f6b8/yolapi/pypi/metadata.py#L84) too.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stefanor** [comment]
Thanks! :)

**Pull request merged**
